### ISSUE TITLE
Some locales are not supported on PayPal

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/PayPalPlugin#131]
I configured the payment method with a sandbox account. After clicking on the place order button in the checkout, i land on the payment page but the paypal form/buttons are missing (instead the credit card tab is filled): 

<img width="500" alt="payment" src="https://user-images.githubusercontent.com/5822554/95053690-0ffc2580-06f1-11eb-91d9-b0b50580778d.png">

And in the console i found this:

> GET https://www.paypal.com/sdk/js?components=hosted-fields,buttons&locale=it&client-id=****&merchant-id=****&intent=capture net::ERR_ABORTED 400

If I call the URL i get this error:

> "Invalid query value for locale: it"

If i call it with it_IT locale it works.
As i can see from the supported locales in the Paypal docs (https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes) they do not support 2-digit locales. 

So probably a mapping between Sylius locales and Paypal locales is needed?

**Comment by Zales0123** [comment]
Hi @LucaGallinari! What prevents you from setting the locale to `it_IT`? It's still the recommended way to do it in Sylius. I understand, that having a regular `it` selectable in the locales list can be confusing, but it's provided by the PHP intl component so we have no control over it.

Still, some mechanism that would map 2-digit locales to their extended, default versions (`it` -> `it_IT`, `pl` -> `pl_PL` etc.) would be definitely an improvement 👌

**Comment by LucaGallinari** [comment]
Hi @Zales0123 sorry for the late response. We used "it" cause this locale is bound to the "it" channel in which you can ship to Italy (it_IT), San Marino (it_SM) and Città del Vaticano (it_VA). So the resulting URL will be mywebsite.com/it and not mywebsite.com/it_IT cause this one would be misleading, we don't want to depend on the region. Moreover, from a SEO perspective is better, cause the language is a generic "italian" not bound to the region.
