### ISSUE TITLE
Log error when an error occured while on PayPal

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/PayPalPlugin#133]
In the PayPalPaymentOnErrorAction class there is a todo regarding this:
https://github.com/Sylius/PayPalPlugin/blob/v1.0.0-RC.1/src/Controller/PayPalPaymentOnErrorAction.php#L23

This is really important cause is not trivial to debug without some logging.

**Comment by Zales0123** [comment]
Agreed 👍 The good thing is we already have the monolog with the PayPal channel configured, so it should be doable quite easily :)
