### ISSUE TITLE
[Feedback] Strange behavior when PayPal is selected in the checkout

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/PayPalPlugin#138]
If we select PayPal as a payment method:

![image](https://user-images.githubusercontent.com/858611/95970266-091b9400-0e10-11eb-8e65-63af434c273c.png)

Then we click on "Continue", and we validate the order, we are never redirected by any way on the payment. It will lead to a lot of issues with customers here "I don't understand" and so on.

**Comment by Zales0123** [comment]
I'm closing this issue, as it cannot be reproduced on the newest version of the plugin. Feel free to reopen if needed :)
