### ISSUE TITLE
[Feedback] Empty addresses after payment?

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/PayPalPlugin#139]
After creating an account from a guest order (using the PayPal button on the product page directly), it seems that I have two addresses in my account, but they are empty:

![image](https://user-images.githubusercontent.com/858611/95970606-729ba280-0e10-11eb-94f7-2712169dcafb.png)

**Comment by Zales0123** [comment]
I think it happens with non-shippable products. When we pay with PayPal, from the product page, we have no place from where we can get the billing (and unneeded shipping) address :/ 

To be honest, I have no idea how it should be handled right now 😄 Hopefull I (or anybody else) would come up with some idea _soon_ 🖖
