### ISSUE TITLE
create-pay-pal-order route fails when using promotion code

### ISSUE THREAD

**Issue by LaskeJu** [Sylius/PayPalPlugin#165]
When I perform a payment, while i using an discount code. The create-pay-pal-order route fails and i cant pay my order.

**Comment by LaskeJu** [comment]
I have added the following code to fix the error:
File: _"Api/CreateOrderApi.php" => "public function create(string $token, PaymentInterface $payment, string $referenceId): array"_

                            'tax_total' => [
                                'currency_code' => $order->getCurrencyCode(),
                                'value' => $payPalItemData['total_tax'],
                            ],

                            //added this:
                            'discount' => [
                                'currency_code' => $order->getCurrencyCode(),
                                'value' => abs($order->getOrderPromotionTotal()) / 100,
                            ]

This is how it works for me.

**Comment by romainguerrero** [comment]
@LaskeJu we have the problem too. Are you able to propose your fix in a PR as it can be shared to everyone ?

**Comment by LaskeJu** [comment]
@romainguerrero added PR #175

**Comment by Zales0123** [comment]
I believe it can be closed due to #175 🖖
