### ISSUE TITLE
Conflict with symplify/package-builder

### ISSUE THREAD

**Issue by armellarcier** [Sylius/PayPalPlugin#173]
This packages `composer.json` marks `symplify/package-builder` versions "^8.3.24" as conflicting.

With sylius 1.8.5 I get `symplify/package-builder` version 8.3.48

Sylius/CodingStandard requires `"symplify/easy-coding-standard": "^7.3 || ^8.1"` ([see here](https://github.com/SyliusLabs/CodingStandard/blob/master/composer.json))

I can't downgrade `symplify/easy-coding-standard` to 7.3 because `sylius/grid-bundle v1.7.5` conflicts with `symplify/smart-file-system v7.3.18`

Here is what happens when I `composer require sylius/paypal-plugin`:

```
Using version ^1.1 for sylius/paypal-plugin
./composer.json has been updated
Running composer update sylius/paypal-plugin
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires sylius/paypal-plugin ^1.1 -> satisfiable by sylius/paypal-plugin[v1.1.0].
    - symplify/easy-coding-standard 8.3.48 requires symplify/package-builder ^8.3.48 -> satisfiable by symplify/package-builder[8.3.48].
    - sylius-labs/coding-standard v3.2.1 requires symplify/easy-coding-standard ^7.3 || ^8.1 -> satisfiable by symplify/easy-coding-standard[8.3.48].
    - symplify/package-builder 8.3.48 conflicts with sylius/paypal-plugin v1.1.0.
    - sylius-labs/coding-standard is locked to version v3.2.1 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I don't see how I can work around this.

So what is the reason for the conflict being declared in PayPalPlugin's composer.json in the first place?

**Comment by armellarcier** [comment]
This commit added the conflict directive

https://github.com/Sylius/PayPalPlugin/commit/4bc2449935a401c02cd0664b1fc774dbe90bf853

**Comment by Zales0123** [comment]
Hi Armel! As far as I remember, there was some problem regarding this package on the Sylius itself. As I see, it's not conflicted anymore, so we can definitely remove it and see what happens :) Would you like to open a PR with such a change? Thanks! 🖖

**Comment by armellarcier** [comment]
Done @Zales0123 but I just removed the line. Aren't there any test CI ?

**Comment by armellarcier** [comment]
@Zales0123 see #174

**Comment by ehibes** [comment]
I just managed to install `sylius/paypal-plugin` with sylius `1.8` downgrading it to `v1.0.0-RC.1` version. Maybe, il would be necessary to update `composer.json` ?
