### ISSUE TITLE
Missing service "monolog.logger.paypal" when installing with composer

### ISSUE THREAD

**Issue by johnkrovitch** [Sylius/PayPalPlugin#182]
Hello,

I have an issue when installing the plugin on Sylius 1.8. The composer installation went fine, but when clearing the cache, the following error appears :

The service "Sylius\PayPalPlugin\Client\PayPalClientInterface" has a dependency on a non-existent service "monolog.logger.paypal".  

And indeed I do not find a declaration for this service in the plugin code. The error is gone when I add the following in the services.yaml (of my application) :

```
services:
    monolog.logger.paypal: '@logger'
```

Is the declaration service missing or it is something else ?

Thank you !

**Comment by Zales0123** [comment]
Hi!

The service is not defined explicitly but is autoregistered with [this configuration](https://github.com/Sylius/PayPalPlugin/blob/master/src/Resources/config/config.yaml#L73). You can check it out with `bin/console debug:container monolog.logger.paypal` Maybe you're missing the configuration import (point 3 from the installation instruction)?

**Comment by johnkrovitch** [comment]
Hi,

you are right, I was missing this part of the installation. Sorry for the disruption.
