### ISSUE TITLE
Notice: Undefined index: migrations_paths

### ISSUE THREAD

**Issue by jeandanyel** [Sylius/PayPalPlugin#184]
Hi 🙂

I tried to install the PayPalPlugin with the command ```composer require sylius/paypal-plugin``` 
but I got the error ```Notice: Undefined index: migrations_paths```.

I tried to remove the line 48 from SyliusPayPalExtension.php and it fixed the issue...

![image](https://user-images.githubusercontent.com/15878787/105522416-34353f80-5cab-11eb-8f97-9811af4bc7d7.png)

**Comment by Zales0123** [comment]
As we support Sylius 1.9 now, I believe it's not an issue anymore 🖖

**Comment by N445** [comment]
I've the same issue on Sylius 1.11 and Symfony 5.4
