### ISSUE TITLE
Dependency conflict Sylius/Sylius and Sylius/PayPalPlugin on Sylius-Standard

### ISSUE THREAD

**Issue by Ferror** [Sylius/PayPalPlugin#256]
https://github.com/Sylius/PayPalPlugin/blob/master/composer.json#L46

Long story short latest Sylius-Sylius 1.12 had changed some code to work with the newest doctrine orm and dbal packages. Like that:
* https://github.com/Sylius/Sylius/commit/431169f1c3c64bdb4408922b18e439cb7be8610a

Yet due to the dependencies matrix and using Sylius/PayPalPlugin on the Sylius-Standard template the pipelines are DEAD 💀. The reason is that the matrix composer installs doctrine/orm version 2.9 which does not have the `getObjectManager` method. 

```
Error:  Migration Sylius\Bundle\CoreBundle\Migrations\Version20161209095131 failed during Execution. Error: "Call to undefined method Doctrine\ORM\Event\OnFlushEventArgs::getObjectManager()"
In ImagesRemoveListener.php line 40:
                                                                               
  [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]                  
  Attempted to call an undefined method named "getObjectManager" of class "Do  
  ctrine\ORM\Event\OnFlushEventArgs".     
```

```
Problem 1
    - Root composer.json requires doctrine/orm ^2.13 -> satisfiable by doctrine/orm[2.13.0, 2.13.1].
    - sylius/paypal-plugin v1.4.0 conflicts with doctrine/orm 2.13.1.
    - sylius/paypal-plugin is locked to version v1.4.0 and an update of this package was not requested.

```

**Comment by Zales0123** [comment]
I believe it's already fixed 🖖 Thank you, @Ferror!
