### ISSUE TITLE
[Bug] Connection to paypal.sylius.com, error

### ISSUE THREAD

**Issue by RomulusED69** [Sylius/PayPalPlugin#278]
**SyliusPayPalPlugin version affected**: 1.5.1

**Description**  
I'm trying to create a new configuration.
When I'm redirected to the authentication page, I get a server error.
![Sélection_319](https://github.com/Sylius/PayPalPlugin/assets/9000452/a51e9cd2-9cfe-4479-bb6b-fa34b06e973c)

**Steps to reproduce**  

**Possible Solution**  
Problem with paypal sylius server ?

**Comment by tejac** [comment]
Getting this error myself. I am trying to add/enable PayPal on a project as per the instructions and cannot seem to get past this.

**Comment by jakubtobiasz** [comment]
@tejac can you retry now, and let me know whether it works :)?

**Comment by RomulusED69** [comment]
@jakubtobiasz
It's OK for me. Thx

**Comment by tejac** [comment]
@jakubtobiasz it does, thank you!

**Comment by jakubtobiasz** [comment]
Great, thanks!
